<!-- 
<table>
<tr>
<th>Title</th>
<th>Artist</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album) : ?>
	<tr>
	<td><?php echo $this->escape($album->title);?></td>
	<td><?php echo $this->escape($album->artist);?></td>
	<td>
	<a href="<?php echo $this->url(array('controller'=>'album',
	'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
	<a href="<?php echo $this->url(array('controller'=>'album',
	'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
	</td>
	</tr>
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->albums, 'Elastic', 'paginationControls.php'); ?>
 -->