<?php
$this->title = "User settings";
$this->headTitle($this->title);

//print_r($this->user);

$updateUrl = $this->url(array('controller'=>'user', 'action'=>'update'), null, true);
$updatepwUrl = $this->url(array('controller'=>'user', 'action'=>'updatepw'), null, true);



?>
<table>
	<tr><td>Username</td><td> <?php echo $this->user['username'];?></td>
	<tr><td>Name</td><td> <?php echo $this->user['name'];?></td>
	<tr><td>Email</td><td> <?php echo $this->user['email'];?></td>
	<tr><td>Role</td><td> <?php echo $this->user['role'];?></td>
</table>
<a href="<?php echo $updateUrl;  ?>">Update account settings</a><br>
<a href="<?php echo $updatepwUrl;  ?>">Change password</a>